### ISSUE TITLE
Any ShaderGraph created with BuiltIn(z3y) gives error message.

### ISSUE THREAD

**Issue by PseudoFossil** [z3y/ShaderGraph#5]
Any ShaderGraph created with the BuiltIn(z3y) gives the following error message:
![Capture](https://github.com/z3y/ShaderGraph/assets/104645780/4ef34112-9ca5-4b72-b4a1-41b05066456c)

This includes otherwise completely blank ShaderGraphs and occurs in both Lit, Unlit, and Flat-Lit ShaderGraphs.

**Comment by z3y** [comment]
What is your unity, shader graph package and core rp package version? Making new graphs works of course, this whole project would be useless if that didnt work

**Comment by GeekAndProud** [comment]
Works fine for me, must be something you're doing wrong
