### ISSUE TITLE
Scene Depth node with Sampling Eye throws shader error

### ISSUE THREAD

**Issue by Krysiek** [z3y/ShaderGraph#8]
When I use _Scene Depth_ node and set _Sampling_ to _Eye_ I've got shader errors. The shader does not work and turns into pink color. 

Errors do not occur when _Sampling_ is set to _Raw_ or _Linear01_.

![obraz](https://github.com/z3y/ShaderGraph/assets/54168895/17ebdd20-27ff-4c8f-a63f-c5ab8c8a6f81)

Example shader:

![obraz](https://github.com/z3y/ShaderGraph/assets/54168895/e6060c9b-b179-4c16-be82-d3ecbe084e25)

Fresh World project created with VRChat Creator Companion.
Unity version: 2022.3.22f
Shader Graph package: 14.0.10
Shader Graph Target (z3y): 1.0.3

**Comment by MidwayMarshall** [comment]
Certainly not an expert in C#/Shaders but it seems to stem from the Orthographic branch ("unity_OrthoParams.w is 1.0 when camera is orthographic, 0.0 when perspective.") of this if/else statement.
![image](https://github.com/z3y/ShaderGraph/assets/8429546/2aea4357-a9b3-46ea-a532-5f5144c48fee)

VR should always be in perspective mode anyways so I just deleted it from SceneDepthNode.cs in the ShaderGraph package and it worked for me. (alternatively maybe you could patch UNITY_MATRIX_I_VP to be UNITY_MATRIX_I_V * UNITY_MATRIX_P to stop  the orthographic section without throwing an error)

![image](https://github.com/z3y/ShaderGraph/assets/8429546/7f16030e-4ccc-4fab-aa51-6ee861e51c64)

Previews with no error and seems to work correctly in scene view

![image](https://github.com/z3y/ShaderGraph/assets/8429546/6fb23048-baf1-4e3e-866b-8542c4ffa4c1)

![image](https://github.com/z3y/ShaderGraph/assets/8429546/18e9fc53-24bf-4aa7-95fc-6b148b123fba)

**Comment by z3y** [comment]
Im glad that you figured it out! I was afraid it would be something in the main package, I'll see if I can fix it still, thanks.

**Comment by z3y** [comment]
Thats fixed the error, but it still wasnt working properly. I've fixed this issue entirely it should be working now.
